### ISSUE TITLE
Compiler error after updating to 0.5.4 from 0.5.3

### ISSUE THREAD

**Issue by bastibense** [geofmureithi/apalis#406]
Hi, after applying the patch update from 0.5.3 to 0.5.4, I suddenly get the following error during compilation:

```
backend-1  | error[E0271]: expected `Ready<RetryPolicy>` to be a future that resolves to `()`, but it resolves to `RetryPolicy`
backend-1  |   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/apalis-0.5.4/src/layers/retry/mod.rs:38:19
backend-1  |    |
backend-1  | 38 |     type Future = future::Ready<Self>;
backend-1  |    |                   ^^^^^^^^^^^^^^^^^^^ expected `()`, found `RetryPolicy`
backend-1  |    |
backend-1  | note: required by a bound in `tower::retry::Policy::Future`
backend-1  |   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-0.5.0/src/retry/policy.rs:48:25
backend-1  |    |
backend-1  | 48 |     type Future: Future<Output = ()>;
backend-1  |    |                         ^^^^^^^^^^^ required by this bound in `Policy::Future`
backend-1  | 
backend-1  | error[E0053]: method `retry` has an incompatible type for trait
backend-1  |   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/apalis-0.5.4/src/layers/retry/mod.rs:40:14
backend-1  |    |
backend-1  | 40 |     fn retry(&self, req: &Req<T>, result: Result<&Res, &Err>) -> Option<Self::Future> {
backend-1  |    |              ^^^^^
backend-1  |    |              |
backend-1  |    |              types differ in mutability
backend-1  |    |              help: change the self-receiver type to match the trait: `&mut self`
backend-1  |    |
backend-1  |    = note: expected signature `fn(&mut RetryPolicy, &mut apalis_core::request::Request<_>, &mut Result<_, apalis_core::error::Error>) -> Option<_>`
backend-1  |               found signature `fn(&RetryPolicy, &apalis_core::request::Request<_>, Result<&_, &apalis_core::error::Error>) -> Option<_>`
backend-1  | 
backend-1  | error[E0053]: method `clone_request` has an incompatible type for trait
backend-1  |   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/apalis-0.5.4/src/layers/retry/mod.rs:53:22
backend-1  |    |
backend-1  | 53 |     fn clone_request(&self, req: &Req<T>) -> Option<Req<T>> {
backend-1  |    |                      ^^^^^
backend-1  |    |                      |
backend-1  |    |                      types differ in mutability
backend-1  |    |                      help: change the self-receiver type to match the trait: `&mut self`
backend-1  |    |
backend-1  |    = note: expected signature `fn(&mut RetryPolicy, &apalis_core::request::Request<_>) -> Option<_>`
backend-1  |               found signature `fn(&RetryPolicy, &apalis_core::request::Request<_>) -> Option<_>`
backend-1  | 
backend-1  |    Compiling axum-range v0.4.0
backend-1  | Some errors have detailed explanations: E0053, E0271.
backend-1  | For more information about an error, try `rustc --explain E0053`.
backend-1  | error: could not compile `apalis` (lib) due to 3 previous errors
backend-1  | warning: build failed, waiting for other jobs to finish...
backend-1  | [Finished running. Exit status: 101]
```

Any ideas? I didn't change anything in my code and it was working without problems for the past months.

Thanks!

**Comment by geofmureithi** [comment]
Seems like something to do with retry and tower.
Also seems like some features bypassed CI. On it

**Comment by geofmureithi** [comment]
Should be resolved by a new release.
